import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { InformationCard } from '../components/Index/InformationCard'
import { PageContainer } from '../components/Core/PageContainer'
import { ImageCard } from '../components/Index/ImageCard'
import { FlexContainer } from '../components/Index/FlexContainer'

const Home: NextPage = () => {
  return (
    <PageContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FlexContainer>
        <InformationCard
          back={'linear-gradient(171.87deg, #035a0e 1%, #0c1d13 120%);'}
          img={
            'https://dapzer.github.io/image-viewer/static/media/5.1104f2fc.jpg'
          }
        >
          <h1>Starfounder</h1>
          <a href={''}>soundcloud </a>
        </InformationCard >
        <ImageCard
          img={
            'https://dapzer.github.io/image-viewer/static/media/5.1104f2fc.jpg'
          }
        />
      </FlexContainer>
    </PageContainer>
  )
}

export default Home
